//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.14 at 09:19:54 AM VET 
//


package com.minotauro.crud.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.minotauro.crud.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.minotauro.crud.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CRUD }
     * 
     */
    public CRUD createCRUD() {
        return new CRUD();
    }

    /**
     * Create an instance of {@link CRUD.Profile }
     * 
     */
    public CRUD.Profile createCRUDProfile() {
        return new CRUD.Profile();
    }

    /**
     * Create an instance of {@link CRUD.ListForm }
     * 
     */
    public CRUD.ListForm createCRUDListForm() {
        return new CRUD.ListForm();
    }

    /**
     * Create an instance of {@link CRUD.Attributes }
     * 
     */
    public CRUD.Attributes createCRUDAttributes() {
        return new CRUD.Attributes();
    }

    /**
     * Create an instance of {@link CRUD.Attributes.Att }
     * 
     */
    public CRUD.Attributes.Att createCRUDAttributesAtt() {
        return new CRUD.Attributes.Att();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link CRUD.EditForm }
     * 
     */
    public CRUD.EditForm createCRUDEditForm() {
        return new CRUD.EditForm();
    }

    /**
     * Create an instance of {@link CRUD.Profile.Create }
     * 
     */
    public CRUD.Profile.Create createCRUDProfileCreate() {
        return new CRUD.Profile.Create();
    }

    /**
     * Create an instance of {@link CRUD.Profile.Update }
     * 
     */
    public CRUD.Profile.Update createCRUDProfileUpdate() {
        return new CRUD.Profile.Update();
    }

    /**
     * Create an instance of {@link CRUD.Profile.Delete }
     * 
     */
    public CRUD.Profile.Delete createCRUDProfileDelete() {
        return new CRUD.Profile.Delete();
    }

    /**
     * Create an instance of {@link CRUD.Profile.View }
     * 
     */
    public CRUD.Profile.View createCRUDProfileView() {
        return new CRUD.Profile.View();
    }

    /**
     * Create an instance of {@link CRUD.ListForm.Column }
     * 
     */
    public CRUD.ListForm.Column createCRUDListFormColumn() {
        return new CRUD.ListForm.Column();
    }

    /**
     * Create an instance of {@link CRUD.ListForm.Paging }
     * 
     */
    public CRUD.ListForm.Paging createCRUDListFormPaging() {
        return new CRUD.ListForm.Paging();
    }

    /**
     * Create an instance of {@link CRUD.Attributes.List }
     * 
     */
    public CRUD.Attributes.List createCRUDAttributesList() {
        return new CRUD.Attributes.List();
    }

    /**
     * Create an instance of {@link CRUD.Attributes.Att.Validator }
     * 
     */
    public CRUD.Attributes.Att.Validator createCRUDAttributesAttValidator() {
        return new CRUD.Attributes.Att.Validator();
    }

}
