//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:09:51 AM VET 
//


package com.minotauro.menu.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cleda.org/menu.xsd}menu-base">
 *       &lt;attribute name="i18nCls" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="i18nKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "entry")
public class Entry
    extends MenuBase
{

    @XmlAttribute(name = "i18nCls")
    protected String i18NCls;
    @XmlAttribute(name = "i18nKey", required = true)
    protected String i18NKey;

    /**
     * Gets the value of the i18NCls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI18NCls() {
        return i18NCls;
    }

    /**
     * Sets the value of the i18NCls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI18NCls(String value) {
        this.i18NCls = value;
    }

    /**
     * Gets the value of the i18NKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI18NKey() {
        return i18NKey;
    }

    /**
     * Sets the value of the i18NKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI18NKey(String value) {
        this.i18NKey = value;
    }

}
