//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.14 at 06:09:51 AM VET 
//


package com.minotauro.menu.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cleda.org/menu.xsd}menu-base">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.cleda.org/menu.xsd}meta-data" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="handler" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="i18nCls" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="i18nKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="priv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scope" type="{http://www.cleda.org/menu.xsd}scope" default="internal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaData"
})
@XmlRootElement(name = "event")
public class Event
    extends MenuBase
{

    @XmlElement(name = "meta-data")
    protected List<MetaData> metaData;
    @XmlAttribute(required = true)
    protected String handler;
    @XmlAttribute(name = "i18nCls")
    protected String i18NCls;
    @XmlAttribute(name = "i18nKey", required = true)
    protected String i18NKey;
    @XmlAttribute
    protected String priv;
    @XmlAttribute
    protected String role;
    @XmlAttribute
    protected Scope scope;

    /**
     * Gets the value of the metaData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metaData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaData }
     * 
     * 
     */
    public List<MetaData> getMetaData() {
        if (metaData == null) {
            metaData = new ArrayList<MetaData>();
        }
        return this.metaData;
    }

    /**
     * Gets the value of the handler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandler() {
        return handler;
    }

    /**
     * Sets the value of the handler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandler(String value) {
        this.handler = value;
    }

    /**
     * Gets the value of the i18NCls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI18NCls() {
        return i18NCls;
    }

    /**
     * Sets the value of the i18NCls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI18NCls(String value) {
        this.i18NCls = value;
    }

    /**
     * Gets the value of the i18NKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getI18NKey() {
        return i18NKey;
    }

    /**
     * Sets the value of the i18NKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setI18NKey(String value) {
        this.i18NKey = value;
    }

    /**
     * Gets the value of the priv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriv() {
        return priv;
    }

    /**
     * Sets the value of the priv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriv(String value) {
        this.priv = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Scope }
     *     
     */
    public Scope getScope() {
        if (scope == null) {
            return Scope.INTERNAL;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scope }
     *     
     */
    public void setScope(Scope value) {
        this.scope = value;
    }

}
