//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.26 at 11:03:15 PM VET 
//


package com.jack.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="preplace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postplace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "transition")
public class Transition {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "preplace", required = true)
    protected String preplace;
    @XmlAttribute(name = "postplace", required = true)
    protected String postplace;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the preplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreplace() {
        return preplace;
    }

    /**
     * Sets the value of the preplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreplace(String value) {
        this.preplace = value;
    }

    /**
     * Gets the value of the postplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostplace() {
        return postplace;
    }

    /**
     * Sets the value of the postplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostplace(String value) {
        this.postplace = value;
    }

}
