//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 05:30:38 PM VET 
//


package com.jack.crud.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cledaCrud.org/crud.xsd}attributes"/>
 *         &lt;element ref="{http://www.cledaCrud.org/crud.xsd}editForm"/>
 *         &lt;element ref="{http://www.cledaCrud.org/crud.xsd}listForm"/>
 *         &lt;element ref="{http://www.cledaCrud.org/crud.xsd}profile"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributes",
    "editForm",
    "listForm",
    "profile"
})
@XmlRootElement(name = "CRUD")
public class CRUD {

    @XmlElement(required = true)
    protected Attributes attributes;
    @XmlElement(required = true)
    protected EditForm editForm;
    @XmlElement(required = true)
    protected ListForm listForm;
    @XmlElement(required = true)
    protected Profile profile;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "desc", required = true)
    protected String desc;
    @XmlAttribute(name = "group", required = true)
    protected String group;

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link Attributes }
     *     
     */
    public Attributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attributes }
     *     
     */
    public void setAttributes(Attributes value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the editForm property.
     * 
     * @return
     *     possible object is
     *     {@link EditForm }
     *     
     */
    public EditForm getEditForm() {
        return editForm;
    }

    /**
     * Sets the value of the editForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditForm }
     *     
     */
    public void setEditForm(EditForm value) {
        this.editForm = value;
    }

    /**
     * Gets the value of the listForm property.
     * 
     * @return
     *     possible object is
     *     {@link ListForm }
     *     
     */
    public ListForm getListForm() {
        return listForm;
    }

    /**
     * Sets the value of the listForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListForm }
     *     
     */
    public void setListForm(ListForm value) {
        this.listForm = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link Profile }
     *     
     */
    public Profile getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile }
     *     
     */
    public void setProfile(Profile value) {
        this.profile = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

}
