//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.24 at 02:58:14 PM UTC 
//


package com.jack.crud;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cledaCrud.org/crud.xsd}validatorChoice"/>
 *       &lt;/sequence>
 *       &lt;attribute name="chained" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validatorChoice"
})
@XmlRootElement(name = "not")
public class Not {

    @XmlElement(required = true)
    protected ValidatorChoice validatorChoice;
    @XmlAttribute(name = "chained", required = true)
    protected boolean chained;

    /**
     * Gets the value of the validatorChoice property.
     * 
     * @return
     *     possible object is
     *     {@link ValidatorChoice }
     *     
     */
    public ValidatorChoice getValidatorChoice() {
        return validatorChoice;
    }

    /**
     * Sets the value of the validatorChoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidatorChoice }
     *     
     */
    public void setValidatorChoice(ValidatorChoice value) {
        this.validatorChoice = value;
    }

    /**
     * Gets the value of the chained property.
     * 
     */
    public boolean isChained() {
        return chained;
    }

    /**
     * Sets the value of the chained property.
     * 
     */
    public void setChained(boolean value) {
        this.chained = value;
    }

}
