//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 09:25:05 AM VET 
//


package com.minotauro.workflow.xml.netpetri;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}meta-data" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}default-doc-section-validate-state" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}default-doc-section-edit-state" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}default-doc-section-view-state" minOccurs="0"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}roles-list"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}place-list"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}trans-list"/>
 *         &lt;element ref="{http://www.cleda.org/net-petri-def.xsd}state-list"/>
 *       &lt;/sequence>
 *       &lt;attribute name="doc-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaData",
    "defaultDocSectionValidateState",
    "defaultDocSectionEditState",
    "defaultDocSectionViewState",
    "rolesList",
    "placeList",
    "transList",
    "stateList"
})
@XmlRootElement(name = "net-petri-def")
public class NetPetriDef {

    @XmlElement(name = "meta-data")
    protected List<MetaData> metaData;
    @XmlElement(name = "default-doc-section-validate-state")
    protected DefaultDocSectionValidateState defaultDocSectionValidateState;
    @XmlElement(name = "default-doc-section-edit-state")
    protected DefaultDocSectionEditState defaultDocSectionEditState;
    @XmlElement(name = "default-doc-section-view-state")
    protected DefaultDocSectionViewState defaultDocSectionViewState;
    @XmlElement(name = "roles-list", required = true)
    protected RolesList rolesList;
    @XmlElement(name = "place-list", required = true)
    protected PlaceList placeList;
    @XmlElement(name = "trans-list", required = true)
    protected TransList transList;
    @XmlElement(name = "state-list", required = true)
    protected StateList stateList;
    @XmlAttribute(name = "doc-type", required = true)
    protected String docType;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the metaData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metaData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaData }
     * 
     * 
     */
    public List<MetaData> getMetaData() {
        if (metaData == null) {
            metaData = new ArrayList<MetaData>();
        }
        return this.metaData;
    }

    /**
     * Gets the value of the defaultDocSectionValidateState property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultDocSectionValidateState }
     *     
     */
    public DefaultDocSectionValidateState getDefaultDocSectionValidateState() {
        return defaultDocSectionValidateState;
    }

    /**
     * Sets the value of the defaultDocSectionValidateState property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultDocSectionValidateState }
     *     
     */
    public void setDefaultDocSectionValidateState(DefaultDocSectionValidateState value) {
        this.defaultDocSectionValidateState = value;
    }

    /**
     * Gets the value of the defaultDocSectionEditState property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultDocSectionEditState }
     *     
     */
    public DefaultDocSectionEditState getDefaultDocSectionEditState() {
        return defaultDocSectionEditState;
    }

    /**
     * Sets the value of the defaultDocSectionEditState property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultDocSectionEditState }
     *     
     */
    public void setDefaultDocSectionEditState(DefaultDocSectionEditState value) {
        this.defaultDocSectionEditState = value;
    }

    /**
     * Gets the value of the defaultDocSectionViewState property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultDocSectionViewState }
     *     
     */
    public DefaultDocSectionViewState getDefaultDocSectionViewState() {
        return defaultDocSectionViewState;
    }

    /**
     * Sets the value of the defaultDocSectionViewState property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultDocSectionViewState }
     *     
     */
    public void setDefaultDocSectionViewState(DefaultDocSectionViewState value) {
        this.defaultDocSectionViewState = value;
    }

    /**
     * Gets the value of the rolesList property.
     * 
     * @return
     *     possible object is
     *     {@link RolesList }
     *     
     */
    public RolesList getRolesList() {
        return rolesList;
    }

    /**
     * Sets the value of the rolesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RolesList }
     *     
     */
    public void setRolesList(RolesList value) {
        this.rolesList = value;
    }

    /**
     * Gets the value of the placeList property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceList }
     *     
     */
    public PlaceList getPlaceList() {
        return placeList;
    }

    /**
     * Sets the value of the placeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceList }
     *     
     */
    public void setPlaceList(PlaceList value) {
        this.placeList = value;
    }

    /**
     * Gets the value of the transList property.
     * 
     * @return
     *     possible object is
     *     {@link TransList }
     *     
     */
    public TransList getTransList() {
        return transList;
    }

    /**
     * Sets the value of the transList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransList }
     *     
     */
    public void setTransList(TransList value) {
        this.transList = value;
    }

    /**
     * Gets the value of the stateList property.
     * 
     * @return
     *     possible object is
     *     {@link StateList }
     *     
     */
    public StateList getStateList() {
        return stateList;
    }

    /**
     * Sets the value of the stateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateList }
     *     
     */
    public void setStateList(StateList value) {
        this.stateList = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocType(String value) {
        this.docType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
