//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.15 at 09:25:05 AM VET 
//


package com.minotauro.workflow.xml.netpetri;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.minotauro.workflow.xml.netpetri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.minotauro.workflow.xml.netpetri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RolesList }
     * 
     */
    public RolesList createRolesList() {
        return new RolesList();
    }

    /**
     * Create an instance of {@link PosPlace }
     * 
     */
    public PosPlace createPosPlace() {
        return new PosPlace();
    }

    /**
     * Create an instance of {@link PlaceList }
     * 
     */
    public PlaceList createPlaceList() {
        return new PlaceList();
    }

    /**
     * Create an instance of {@link NetPetriDef }
     * 
     */
    public NetPetriDef createNetPetriDef() {
        return new NetPetriDef();
    }

    /**
     * Create an instance of {@link MetaData }
     * 
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link Auto }
     * 
     */
    public Auto createAuto() {
        return new Auto();
    }

    /**
     * Create an instance of {@link Work }
     * 
     */
    public Work createWork() {
        return new Work();
    }

    /**
     * Create an instance of {@link StateList }
     * 
     */
    public StateList createStateList() {
        return new StateList();
    }

    /**
     * Create an instance of {@link DefaultDocSectionValidateState }
     * 
     */
    public DefaultDocSectionValidateState createDefaultDocSectionValidateState() {
        return new DefaultDocSectionValidateState();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link TransList }
     * 
     */
    public TransList createTransList() {
        return new TransList();
    }

    /**
     * Create an instance of {@link Trans }
     * 
     */
    public Trans createTrans() {
        return new Trans();
    }

    /**
     * Create an instance of {@link DefaultDocSectionViewState }
     * 
     */
    public DefaultDocSectionViewState createDefaultDocSectionViewState() {
        return new DefaultDocSectionViewState();
    }

    /**
     * Create an instance of {@link DefaultDocSectionEditState }
     * 
     */
    public DefaultDocSectionEditState createDefaultDocSectionEditState() {
        return new DefaultDocSectionEditState();
    }

    /**
     * Create an instance of {@link PrePlace }
     * 
     */
    public PrePlace createPrePlace() {
        return new PrePlace();
    }

    /**
     * Create an instance of {@link TransSet }
     * 
     */
    public TransSet createTransSet() {
        return new TransSet();
    }

    /**
     * Create an instance of {@link DocSectionState }
     * 
     */
    public DocSectionState createDocSectionState() {
        return new DocSectionState();
    }

    /**
     * Create an instance of {@link StateSet }
     * 
     */
    public StateSet createStateSet() {
        return new StateSet();
    }

    /**
     * Create an instance of {@link DefaultDocSectionState }
     * 
     */
    public DefaultDocSectionState createDefaultDocSectionState() {
        return new DefaultDocSectionState();
    }

    /**
     * Create an instance of {@link StateGrp }
     * 
     */
    public StateGrp createStateGrp() {
        return new StateGrp();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

}
